####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                                                                              | #
# |                                                                                              | #
# |     ░░░░░░        ░█████╗░░░░██╗░░░██╗████████╗██╗██╗░░░░░░██████╗        ░░░░░░             | #
# |     ░░░░░░        ██╔══██╗░░░██║░░░██║╚══██╔══╝██║██║░░░░░██╔════╝        ░░░░░░             | #
# |     █████╗        ██║░░╚═╝░░░██║░░░██║░░░██║░░░██║██║░░░░░╚█████╗░        █████╗             | #
# |     ╚════╝        ██║░░██╗░░░██║░░░██║░░░██║░░░██║██║░░░░░░╚═══██╗        ╚════╝             | #
# |     ░░░░░░        ╚█████╔╝██╗╚██████╔╝░░░██║░░░██║███████╗██████╔╝        ░░░░░░             | #
# |     ░░░░░░        ░╚════╝░╚═╝░╚═════╝░░░░╚═╝░░░╚═╝╚══════╝╚═════╝░        ░░░░░░             | #
# |                                                                                              | #
# |                         𝘼 𝙥𝙧𝙖𝙩𝙞𝙘𝙖𝙡, 𝙨𝙚𝙘𝙪𝙧𝙚 𝙥𝙡𝙪𝙜𝙞𝙣 𝙩𝙤 𝙢𝙖𝙠𝙚 𝙮𝙤𝙪𝙧 𝙡𝙞𝙛𝙚 𝙚𝙖𝙨𝙞𝙚𝙧.                        | #
# |                                                                                              | #
# |                                © 2023 - Powered by me.imcj                                   | #
# |                                                                                              | #
# |                                                                                              | #
# |  Para um melhor entendimento deste arquivo acesse nossa documentação:                        | #
# |   ==> https://return-3.gitbook.io/cchat/                                                     | #
# |                                                                                              | #
# |  Local para definir ou desativar funções.                                                    | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# Área designada para desativa ou ativar funções,
# padrões do Plugin.

# Área de Menus
# ----

Bigorna:
  habilitado: true

Craft:
  habilitado: true

EChest:
  habilitado: true

# Área de comandos de Administração
# ----

InvSee:
  habilitado: true

Vanish:
  habilitado: true

Voar:
  habilitado: true

Sudo:
  habilitado: true


Luz:
  habilitado: true

# Utilidades
# ----

Ping:
  habilitado: true

Cores:
  habilitado: true

Chapeu:
  habilitado: true

Helloworldcmd:
  habilitado: false